/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.presentation;

import br.com.estoque.bussines.facade.Options;
import br.com.estoque.bussines.facade.TransacaoIn;
import br.com.estoque.common.RoloTableModel;
import br.com.estoque.entity.RoloEntity;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alirio
 */
public class EstoqueForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form EstoqueForm
     */
    private final TransacaoIn transacaoIn;
    private RoloTableModel roloTableModel;
    private Boolean update = false;
    private RoloEntity entity;

    public EstoqueForm(TransacaoIn tin) {
        initComponents();
        transacaoIn = tin;
        roloTableModel = new RoloTableModel();
        tblRolos.setModel(roloTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbPassagem = new javax.swing.JComboBox();
        tfSerial = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        cbRaiacao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbLocal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tfTag = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRolos = new javax.swing.JTable();
        btnAddRolo = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lbIcon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        peLog = new javax.swing.JTextPane();
        btnApagar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Cadastro de Rolo");

        jLabel1.setText("Serial");

        cbPassagem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "C2Af", "C5", "T3Gr", "T1", "T2" }));

        tfSerial.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfSerialCaretUpdate(evt);
            }
        });

        jLabel2.setText("Raiação");

        cbRaiacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "250", "350", "500", "600", "625", "750", "850" }));

        jLabel3.setText("Localização");

        cbLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Estoque", "Oficina", "Fortaleza", "Instalado", "Transito" }));
        cbLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLocalItemStateChanged(evt);
            }
        });

        jLabel4.setText("Passagem");

        tfTag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTag.setText("T A G");
        tfTag.setEnabled(false);

        tblRolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"45433", "250", "T5Gr", "Estoque"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial", "Raiação", "Passagem", "Localização"
            }
        ));
        jScrollPane1.setViewportView(tblRolos);

        btnAddRolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/add-2-icon.png"))); // NOI18N
        btnAddRolo.setText("Adicionar");
        btnAddRolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoloActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/edit-icon.png"))); // NOI18N
        btnEdit.setText("Atualizar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png"))); // NOI18N

        peLog.setEditable(false);
        peLog.setFocusable(false);
        jScrollPane3.setViewportView(peLog);

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png"))); // NOI18N
        btnApagar.setText("Apagar   ");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIcon)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPassagem, 0, 98, Short.MAX_VALUE)
                                    .addComponent(cbRaiacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnAddRolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTag, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbLocal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lbIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbRaiacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddRolo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApagar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbIcon, tfSerial});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSerialCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfSerialCaretUpdate
        if (tfSerial.getCaretPosition() > 1) {
            roloTableModel = new RoloTableModel(new ArrayList(transacaoIn.checarSerial(tfSerial.getText())));
            tblRolos.setModel(roloTableModel);
            if (roloTableModel.getRowCount() > 0) {
                lbIcon.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/854_16x16.png")));
            } else {
                lbIcon.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));
            }
        }
    }//GEN-LAST:event_tfSerialCaretUpdate

    private void btnAddRoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoloActionPerformed
        RoloEntity r = new RoloEntity();
        r.setSerial(tfSerial.getText());
        r.setRaiacao(cbRaiacao.getSelectedItem().toString());
        r.setPassagem(cbPassagem.getSelectedItem().toString());
        r.setLocalizacao(cbLocal.getSelectedItem().toString());
        if (cbLocal.getSelectedIndex() == 4) // instalado
        {
            r.setTag(tfTag.getText());
        }
        Options op;
        op = transacaoIn.adicionarEstoque(r);
        if (op == Options.OK) {
            peLog.setText(peLog.getText() + "\n+++Cadastrado com sucesso!");
        } else {
            peLog.setText(peLog.getText() + "\n---Não cadastrado!");
        }
    }//GEN-LAST:event_btnAddRoloActionPerformed

    private void cbLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLocalItemStateChanged
        if (cbLocal.getSelectedIndex() == 4) { // instalado
            tfTag.setEnabled(true);
            tfTag.setText("");
        } else {
            tfTag.setEnabled(false);

        }
    }//GEN-LAST:event_cbLocalItemStateChanged

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tblRolos.getSelectedRow();
        if (row == -1) {
            return;
        }

        if (!update) {
            btnApagar.setText("Cancelar");
            btnEdit.setText("Salvar");
            btnAddRolo.setEnabled(false);
            entity = roloTableModel.getRoloEntity(row);
            tfTag.setText(entity.getTag());
            tfSerial.setText(entity.getSerial());
            tfSerial.setEditable(false);
            update = true;
        } else {
            btnApagar.setText("Deletar");
            btnEdit.setText("Atualizar");
            btnAddRolo.setEnabled(true);
            tfSerial.setEditable(true);
            update = false;
            entity.setSerial(tfSerial.getText());
            entity.setRaiacao(cbRaiacao.getSelectedItem().toString());
            entity.setPassagem(cbPassagem.getSelectedItem().toString());
            entity.setLocalizacao(cbLocal.getSelectedItem().toString());
            if (cbLocal.getSelectedIndex() == 4) // instalado
            {
                entity.setTag(tfTag.getText());
            }
            transacaoIn.atualizarEstoque(entity);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        if (btnApagar.getText().equalsIgnoreCase("Cancelar")) {
            btnApagar.setText("Deletar");
            btnEdit.setText("Atualizar");
            btnAddRolo.setEnabled(true);
            tfSerial.setEditable(true);
            update = false;
        }else{
            int row = tblRolos.getSelectedRow();
            RoloEntity r = roloTableModel.getRoloEntity(row);
            int option = JOptionPane.showConfirmDialog(this, "Deseja realmente pagar o rolo\n"
                    +"Serial: "+r.getSerial()+"\n"
                    +"Passagem: "+r.getPassagem()+"\n"
                    +"Local: "+r.getLocalizacao(), JOptionPane.OPTIONS_PROPERTY,JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){ // yes
                transacaoIn.removerRolo(r);
            }
            
        }
    }//GEN-LAST:event_btnApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRolo;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox cbLocal;
    private javax.swing.JComboBox cbPassagem;
    private javax.swing.JComboBox cbRaiacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JTextPane peLog;
    private javax.swing.JTable tblRolos;
    private javax.swing.JFormattedTextField tfSerial;
    private javax.swing.JFormattedTextField tfTag;
    // End of variables declaration//GEN-END:variables
}
