/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.presentation;

import br.com.estoque.bussines.facade.InstallIn;
import br.com.estoque.bussines.facade.Options;
import br.com.estoque.bussines.facade.TransacaoIn;
import br.com.estoque.entity.InstallEntity;
import br.com.estoque.entity.RoloEntity;
import java.util.ArrayList;
import java.util.Collection;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alirio
 */
public class InstalacaoForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form InstalacaoForm
     */
    private static final Integer SAIDA_1 = 0;
    private static final Integer SAIDA_2 = 1;
    private static final Integer ENTRADA_1 = 2;
    private static final Integer ENTRADA_2 = 3;
    private final List<RoloEntity> lstRolo;
    private final TransacaoIn transacaoIn;
    private final InstallIn installInter;
    private Collection<RoloEntity> entityList;
    private InstallEntity install;

    public InstalacaoForm(TransacaoIn tIn, InstallIn Iin) {
        transacaoIn = tIn;
        installInter = Iin;
        initComponents();
        install = new InstallEntity();
        lstRolo = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfSaida1 = new javax.swing.JFormattedTextField();
        tfSaida2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfEntrada1 = new javax.swing.JFormattedTextField();
        tfEntrada2 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfHorimetro = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        cbDiagrama = new javax.swing.JComboBox();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);

        jLabel2.setText(" TAG:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída"));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png"))); // NOI18N

        tfSaida1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfSaida1CaretUpdate(evt);
            }
        });
        tfSaida1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSaida1FocusLost(evt);
            }
        });
        tfSaida1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSaida1MouseClicked(evt);
            }
        });

        tfSaida2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfSaida2CaretUpdate(evt);
            }
        });
        tfSaida2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSaida2FocusLost(evt);
            }
        });
        tfSaida2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSaida2MouseClicked(evt);
            }
        });

        jLabel1.setText("T4 Fn");

        jLabel3.setText("T4 Fn");

        jLabel7.setText("Instalado");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setText("Instalado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfSaida1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfSaida2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfSaida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfSaida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel12, jLabel3, jLabel4, jLabel5, jLabel7, tfSaida1, tfSaida2});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada"));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png"))); // NOI18N

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png"))); // NOI18N

        tfEntrada1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfEntrada1CaretUpdate(evt);
            }
        });
        tfEntrada1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEntrada1FocusLost(evt);
            }
        });
        tfEntrada1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEntrada1MouseClicked(evt);
            }
        });

        tfEntrada2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfEntrada2CaretUpdate(evt);
            }
        });
        tfEntrada2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEntrada2FocusLost(evt);
            }
        });
        tfEntrada2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfEntrada2MouseClicked(evt);
            }
        });

        jLabel14.setText("T4 Fn");

        jLabel15.setText("T4 Fn");

        jLabel16.setText("Estoque");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel17.setText("Estoque");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tfEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(tfEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel13, jLabel15, jLabel16, tfEntrada2});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel14, jLabel17, jLabel6, tfEntrada1});

        jLabel8.setText("Horimetro:");

        jLabel9.setText("Diagrama:");

        cbDiagrama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Moinho A", "Moinho B", "Moinho C" }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTag, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfHorimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(tfHorimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cbDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSalvar, cbDiagrama, jLabel2, jLabel8, jLabel9, tfHorimetro, tfTag});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSaida1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfSaida1CaretUpdate
        if (tfSaida1.getCaretPosition() > 1) {
            entityList = transacaoIn.checarSerial(tfSaida1.getText());
        } else {
            jLabel1.setText("");
            jLabel12.setText("");
            jLabel4.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));
        }
    }//GEN-LAST:event_tfSaida1CaretUpdate

    private void tfSaida1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSaida1MouseClicked
        if (evt.getClickCount() == 2) {
            if (!tfSaida1.isEnabled()) {
                tfSaida1.setEnabled(true);
                tfSaida1.setText("");
                jLabel1.setText("");
                jLabel12.setText("");
                jLabel4.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));
            }
        }
    }//GEN-LAST:event_tfSaida1MouseClicked

    private void tfSaida2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfSaida2CaretUpdate
        if (tfSaida2.getCaretPosition() > 1) {
            entityList = transacaoIn.checarSerial(tfSaida2.getText());
        } else {
            jLabel3.setText("");
            jLabel7.setText("");
            jLabel5.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));

        }
    }//GEN-LAST:event_tfSaida2CaretUpdate

    private void tfSaida2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSaida2MouseClicked
        if (evt.getClickCount() > 1) {
            if (!tfSaida2.isEnabled()) {
                tfSaida2.setEnabled(true);
                tfSaida2.setText("");
                jLabel3.setText("");
                jLabel7.setText("");
                jLabel5.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));
            }
        }
    }//GEN-LAST:event_tfSaida2MouseClicked

    private void tfEntrada1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfEntrada1CaretUpdate
        if (tfEntrada1.getCaretPosition() > 1) {
            entityList = transacaoIn.checarSerial(tfEntrada1.getText());
        } else {
            jLabel14.setText("");
            jLabel17.setText("");
            jLabel6.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));
        }
    }//GEN-LAST:event_tfEntrada1CaretUpdate

    private void tfEntrada2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfEntrada2CaretUpdate
        if (tfEntrada2.getCaretPosition() > 1) {
            entityList = transacaoIn.checarSerial(tfEntrada2.getText());
        } else {
            jLabel15.setText("");
            jLabel16.setText("");
            jLabel13.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));
        }
    }//GEN-LAST:event_tfEntrada2CaretUpdate

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        install = new InstallEntity();
        install.setDataInstalacao(GregorianCalendar.getInstance().getTime());
        install.setDiagrama(cbDiagrama.getSelectedItem().toString());
        install.setHorimetro(Long.parseLong(tfHorimetro.getText()));
        install.setTag(tfTag.getText());
        install.setRolo(new HashSet<>(lstRolo));
        // persist install
        Options res = installInter.adicionarInstalacao(install);
        if (res == Options.OK) {
            Options op = transacaoIn.atualizarEstoque(install.getRolo().iterator());
            if (op == Options.NOTOK) {
                // rollback
            } else {
                JOptionPane.showMessageDialog(this, "Sucesso!");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tfSaida1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSaida1FocusLost
        // checa se lista esta vazia, depois se contem apenas um RoloEntity, depois se o caret é igual ou maior q 5.
        if (!entityList.isEmpty() && entityList.size() == 1 && tfSaida1.getCaretPosition() >= 5) {
            RoloEntity e = entityList.iterator().next(); // recupera a entity
            tfSaida1.setEnabled(false); //  desabilita textfield
            jLabel1.setText(e.getPassagem());
            jLabel12.setText(e.getLocalizacao());
            jLabel4.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/854_16x16.png")));
            e.setLocalizacao("Oficina"); // muda estado do rolo
            lstRolo.add(SAIDA_1, e); // adicionar rolo a lista na posição SAIDA_1 = 0;
            if(lstRolo.get(0).getTag().equals(lstRolo.get(1).getTag()))
                tfTag.setText(lstRolo.get(0).getTag());            
        }
    }//GEN-LAST:event_tfSaida1FocusLost

    private void tfSaida2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSaida2FocusLost
        if (!entityList.isEmpty() && entityList.size() == 1 && tfSaida2.getCaretPosition() >= 5) {
            RoloEntity e = entityList.iterator().next();
            tfSaida2.setText(e.getSerial());
            tfSaida2.setEnabled(false);
            jLabel3.setText(e.getPassagem());
            jLabel7.setText(e.getLocalizacao());
            jLabel5.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/854_16x16.png")));
            e.setLocalizacao("Oficina");
            lstRolo.add(SAIDA_2, e);
            if(lstRolo.get(0).getTag().equals(lstRolo.get(1).getTag()))
                tfTag.setText(lstRolo.get(0).getTag());
        }
    }//GEN-LAST:event_tfSaida2FocusLost

    private void tfEntrada1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEntrada1FocusLost
        if (!entityList.isEmpty() && entityList.size() == 1 && tfEntrada1.getCaretPosition() >= 5) {
            RoloEntity e = entityList.iterator().next();
            tfEntrada1.setText(e.getSerial());
            tfEntrada1.setEnabled(false);
            jLabel14.setText(e.getPassagem());
            jLabel17.setText(e.getLocalizacao());
            jLabel6.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/854_16x16.png")));
            e.setLocalizacao("Instalado");
            lstRolo.add(ENTRADA_1, e);
        }
    }//GEN-LAST:event_tfEntrada1FocusLost

    private void tfEntrada2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEntrada2FocusLost
        if (!entityList.isEmpty() && entityList.size() == 1 && tfEntrada2.getCaretPosition() >= 5) {
            RoloEntity e = entityList.iterator().next();
            tfEntrada2.setText(e.getSerial());
            tfEntrada2.setEnabled(false);
            jLabel15.setText(e.getPassagem());
            jLabel16.setText(e.getLocalizacao());
            jLabel13.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/854_16x16.png")));
            e.setLocalizacao("Instalado");
            lstRolo.add(ENTRADA_2, e);
        }
    }//GEN-LAST:event_tfEntrada2FocusLost

    private void tfEntrada1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEntrada1MouseClicked
        if (evt.getClickCount() > 1) {
            if (!tfEntrada1.isEnabled()) {
                tfEntrada1.setEnabled(true);
                tfEntrada1.setText("");
                jLabel17.setText("");
                jLabel14.setText("");
                jLabel6.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));
            }
        }
    }//GEN-LAST:event_tfEntrada1MouseClicked

    private void tfEntrada2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEntrada2MouseClicked
        if (evt.getClickCount() > 1) {
            if (!tfEntrada2.isEnabled()) {
                tfEntrada2.setEnabled(true);
                tfEntrada2.setText("");
                jLabel16.setText("");
                jLabel15.setText("");
                jLabel13.setIcon(new ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/x.png")));
            }
        }
    }//GEN-LAST:event_tfEntrada2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbDiagrama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JFormattedTextField tfEntrada1;
    private javax.swing.JFormattedTextField tfEntrada2;
    private javax.swing.JFormattedTextField tfHorimetro;
    private javax.swing.JFormattedTextField tfSaida1;
    private javax.swing.JFormattedTextField tfSaida2;
    private javax.swing.JTextField tfTag;
    // End of variables declaration//GEN-END:variables

    private class ThreadImpl extends Thread {

        private final RoloEntity e;

        public ThreadImpl(Runnable target, RoloEntity e) {
            super(target);
            this.e = e;
        }

        @Override
        public void run() {
            tfSaida1.setText(e.getSerial());
            this.stop();
        }
    }
}
