/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.presentation;

import br.com.estoque.bussines.facade.InstallService;
import br.com.estoque.bussines.facade.Transacao;
import br.com.estoque.jasper.Jasper;
import br.com.estoque.persistencia.Factory;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author Alirio
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private final EstoqueForm eForm;
    private final RemessaForm rForm;
    private final InstalacaoForm iForm;
    private final Transacao transacao;
    private final InstallService iservice;
    private final Jasper relatorios;
    
    public MainForm() {
        System.out.println(this.getClass().getClassLoader().getResource("").getPath());
        setUI();
        initComponents();
        Factory f = new Factory();
        transacao = new Transacao(f);
        iservice = new InstallService(f);
        eForm = new EstoqueForm(transacao);
        rForm = new RemessaForm(transacao);
        iForm = new InstalacaoForm(transacao,iservice);
        desktop.add(eForm);        
        desktop.add(rForm);        
        desktop.add(iForm); 
        relatorios = new Jasper(transacao, "");
        /*try {
            relatorios.print();
        } catch (JRException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }
    public static void setUI(){        
        try{
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
                if ("Metal".equals(info.getName())) {
                UIManager.setLookAndFeel(info.getClassName());
                break;
                }                
            }
            //UIManager.setLookAndFeel(new Plastic3DLookAndFeel());
        }catch(/*UnsupportedLookAndFeelException*/Exception u){
            u.printStackTrace();
	}
        UIManager.put( "nimbusBase", new Color( 59, 140, 47 ) );  
        UIManager.put( "nimbusBlueGrey", new Color( 170, 190, 184 ) );  
        UIManager.put( "control", new Color( 214, 223, 220 ) );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnRemessa = new javax.swing.JButton();
        btnInstalacao = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(5, 0, 0, 0));
        jToolBar1.setOpaque(false);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/new.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnNovo.setMaximumSize(new java.awt.Dimension(80, 60));
        btnNovo.setMinimumSize(new java.awt.Dimension(80, 60));
        btnNovo.setPreferredSize(new java.awt.Dimension(80, 60));
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/drawer.png"))); // NOI18N
        jButton1.setText("Estoque");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButton1.setMaximumSize(new java.awt.Dimension(80, 60));
        jButton1.setMinimumSize(new java.awt.Dimension(80, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        btnRemessa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/globe.png"))); // NOI18N
        btnRemessa.setText("Remessa");
        btnRemessa.setFocusable(false);
        btnRemessa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemessa.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnRemessa.setMaximumSize(new java.awt.Dimension(80, 60));
        btnRemessa.setMinimumSize(new java.awt.Dimension(80, 60));
        btnRemessa.setPreferredSize(new java.awt.Dimension(80, 60));
        btnRemessa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemessa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemessaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRemessa);

        btnInstalacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/estoque/presentation/imagens/gear.png"))); // NOI18N
        btnInstalacao.setText("Intalação");
        btnInstalacao.setFocusable(false);
        btnInstalacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInstalacao.setMargin(new java.awt.Insets(2, 4, 2, 4));
        btnInstalacao.setMaximumSize(new java.awt.Dimension(80, 60));
        btnInstalacao.setMinimumSize(new java.awt.Dimension(80, 60));
        btnInstalacao.setPreferredSize(new java.awt.Dimension(80, 60));
        btnInstalacao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInstalacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstalacaoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInstalacao);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(desktop))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemessaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemessaActionPerformed
        rForm.setVisible(true);
    }//GEN-LAST:event_btnRemessaActionPerformed

    private void btnInstalacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstalacaoActionPerformed
        iForm.setVisible(true);
    }//GEN-LAST:event_btnInstalacaoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        eForm.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       setUI();
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstalacao;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemessa;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
