/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.presentation;

import br.com.estoque.bussines.facade.Options;
import br.com.estoque.bussines.facade.TransacaoIn;
import br.com.estoque.common.JCalendar;
import br.com.estoque.common.RemessaTableModel;
import br.com.estoque.common.RoloTableModel;
import br.com.estoque.entity.RemessaEntity;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alirio
 */
public class RemessaForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemessaForm
     */
    private final TransacaoIn transacaoIn;
    private RoloTableModel roloTableModel, rolosSendTableModel, showtableModel;
    private RemessaTableModel remessaTableModel;
    
    public RemessaForm(TransacaoIn tin) {
        initComponents();
        transacaoIn = tin;
        roloTableModel = new RoloTableModel(); 
        rolosSendTableModel = new RoloTableModel();
        remessaTableModel = new RemessaTableModel(transacaoIn.listarRemessas());
        
        tblRemessaGeral.setModel(remessaTableModel);
        tblRolos.setModel(roloTableModel);
        tblRolosSend.setModel(rolosSendTableModel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdRemessa = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        tfDestino1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfRemessa1 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tfNF1 = new javax.swing.JFormattedTextField();
        tfMov1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblShowRemessa = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRolos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfSerial = new javax.swing.JTextField();
        btnAddRoloToSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfDestino = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfRemessa = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNF = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tfMov = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRolosSend = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lbQtd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new JCalendar(true);
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRemessaGeral = new javax.swing.JTable();

        jdRemessa.setAlwaysOnTop(true);
        jdRemessa.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel3.setText("Destino:");

        tfDestino1.setEditable(false);
        tfDestino1.setText("Fortaleza");
        tfDestino1.setEnabled(false);

        jLabel8.setText("Remessa:");

        tfRemessa1.setEditable(false);
        tfRemessa1.setEnabled(false);

        jLabel9.setText("Nota Fiscal:");

        tfNF1.setEditable(false);
        tfNF1.setEnabled(false);

        tfMov1.setEditable(false);
        tfMov1.setEnabled(false);

        jLabel10.setText("Motivo:");

        tblShowRemessa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial", "Passagem", "Raiação", "Localização"
            }
        ));
        jScrollPane4.setViewportView(tblShowRemessa);

        jButton1.setText("Entrada todos");

        jButton2.setText("Entrada");

        jButton3.setText("Gerar Relatório");

        jButton4.setText("Atualizar");

        jButton5.setText("Confirmar recebimento no destino");

        javax.swing.GroupLayout jdRemessaLayout = new javax.swing.GroupLayout(jdRemessa.getContentPane());
        jdRemessa.getContentPane().setLayout(jdRemessaLayout);
        jdRemessaLayout.setHorizontalGroup(
            jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdRemessaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jdRemessaLayout.createSequentialGroup()
                        .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jdRemessaLayout.createSequentialGroup()
                                .addComponent(tfDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRemessa1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNF1))
                            .addComponent(tfMov1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdRemessaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jdRemessaLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jdRemessaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jdRemessaLayout.setVerticalGroup(
            jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdRemessaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfRemessa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfNF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMov1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdRemessaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);

        tblRolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"45433", "250", "T5Gr", "Estoque"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial", "Raiação", "Passagem", "Localização"
            }
        ));
        jScrollPane1.setViewportView(tblRolos);

        jLabel2.setText("Serial");

        tfSerial.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfSerialCaretUpdate(evt);
            }
        });

        btnAddRoloToSend.setText("Adicionar");
        btnAddRoloToSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoloToSendActionPerformed(evt);
            }
        });

        jLabel1.setText("Destino:");

        tfDestino.setText("Fortaleza");

        jLabel5.setText("Remessa:");

        jLabel6.setText("Nota Fiscal:");

        jLabel7.setText("Motivo:");

        tblRolosSend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"45433", "250", "T5Gr", "Estoque"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial", "Raiação", "Passagem", "Localização"
            }
        ));
        tblRolosSend.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tblRolosSendComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                tblRolosSendComponentRemoved(evt);
            }
        });
        jScrollPane2.setViewportView(tblRolosSend);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lbQtd.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbQtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQtd.setText("00");
        lbQtd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbQtd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setText("Data:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRemessa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfMov, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddRoloToSend))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddRoloToSend))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfRemessa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbQtd)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox1, jLabel1, jLabel4, jLabel5, jLabel6, jLabel7, tfDestino, tfMov, tfNF, tfRemessa});

        jTabbedPane1.addTab("Enviar", jPanel1);

        tblRemessaGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRemessaGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRemessaGeralMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblRemessaGeral);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receber", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSerialCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfSerialCaretUpdate
        if(tfSerial.getCaretPosition() > 1){            
            roloTableModel = new RoloTableModel(new ArrayList(transacaoIn.checarSerial(tfSerial.getText())));
            tblRolos.setModel(roloTableModel);            
        }
    }//GEN-LAST:event_tfSerialCaretUpdate

    private void btnAddRoloToSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoloToSendActionPerformed
        int row = tblRolos.getSelectedRow();
        if(row == -1) return;
        
        if(rolosSendTableModel.existe(roloTableModel.getRoloEntity(row))) return;
        
        rolosSendTableModel.adicionarRolo(roloTableModel.getRoloEntity(row)); 
        lbQtd.setText(Integer.toString(tblRolosSend.getRowCount()));
    }//GEN-LAST:event_btnAddRoloToSendActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int row = tblRolosSend.getSelectedRow();
        if(row == -1) return;
        
        rolosSendTableModel.removerLinha(row);        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int count = tblRolosSend.getRowCount();
        if(count == 0) return;        
        RemessaEntity remessa = new RemessaEntity();
        remessa.setDataEnvio(GregorianCalendar.getInstance().getTime());
        remessa.setDestino(tfDestino.getText());
        remessa.setMotivo(tfMov.getText());
        remessa.setNumNotaFiscal(Integer.parseInt(tfNF.getText()));
        remessa.setQtdRolos(count);
        remessa.setQtdRolosPendentes(count);
        remessa.setNumRemessa(Long.parseLong(tfRemessa.getText()));
        
        
        // navega por todos os rolos e seta o estatus "Em Transito" no array
        for(int i=0;i<count;i++){      
            rolosSendTableModel.setRoloLocalizacao("Transito", i);
            System.out.println("For: "+i+" Rolo Serial: "+rolosSendTableModel.getRoloEntity(i).getSerial());
        }
        remessa.setRolo(new HashSet<>(rolosSendTableModel.getListRolosEntity()));
        
        remessa.setRe(remessa.getRolo().iterator().next()); // teste
        // faz a persistencia no banco
        Options op = transacaoIn.adicionarRemessa(remessa);
        // checa de tudo ocorreu bem
        if(op == Options.OK){
            // atualiza o novo status dos rolos no banco RoloEntity
            op = transacaoIn.atualizarEstoque(rolosSendTableModel.getListRolosEntity().iterator());
            remessaTableModel.adicionarRemessa(remessa);
            // tudo ok, limpa os campos
            tfDestino.setText("");
            tfMov.setText("");
            tfNF.setText("");
            tfRemessa.setText("");
            rolosSendTableModel.limparTabela();
            lbQtd.setText(Integer.toString(roloTableModel.getRowCount()));
            // Se não deu certo, então exclui a remessa
            if(op == Options.NOTOK){
                transacaoIn.excluirRemessa(remessa);
                remessaTableModel.removerRemessaEntity(remessa);
            }        
        }else
            JOptionPane.showMessageDialog(this,"Erro ao tentar persistir no banco. Tabela RemessaEntity");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblRolosSendComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tblRolosSendComponentAdded
        
    }//GEN-LAST:event_tblRolosSendComponentAdded

    private void tblRolosSendComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tblRolosSendComponentRemoved
        
    }//GEN-LAST:event_tblRolosSendComponentRemoved

    private void tblRemessaGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRemessaGeralMouseClicked
        if(evt.getClickCount() == 2){
            int row = tblRemessaGeral.getSelectedRow();
            if(row == -1) return;
            showtableModel = new RoloTableModel(new ArrayList<>(remessaTableModel.getRemessa(row).getRolo()));
            tblShowRemessa.setModel(showtableModel);
            RemessaEntity e = remessaTableModel.getRemessa(row);
            tfDestino1.setText(e.getDestino());
            tfMov1.setText(e.getMotivo());
            tfNF1.setText(Integer.toString(e.getNumNotaFiscal()));
            tfRemessa1.setText(Long.toString(e.getNumRemessa()));
            jdRemessa.pack();
            jdRemessa.setVisible(true);
            
        }
            
    }//GEN-LAST:event_tblRemessaGeralMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoloToSend;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jdRemessa;
    private javax.swing.JLabel lbQtd;
    private javax.swing.JTable tblRemessaGeral;
    private javax.swing.JTable tblRolos;
    private javax.swing.JTable tblRolosSend;
    private javax.swing.JTable tblShowRemessa;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfDestino1;
    private javax.swing.JTextField tfMov;
    private javax.swing.JTextField tfMov1;
    private javax.swing.JFormattedTextField tfNF;
    private javax.swing.JFormattedTextField tfNF1;
    private javax.swing.JFormattedTextField tfRemessa;
    private javax.swing.JFormattedTextField tfRemessa1;
    private javax.swing.JTextField tfSerial;
    // End of variables declaration//GEN-END:variables
}
