/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gma.expedicao.presentation;

import br.com.gma.cliente.common.AutenticadorInterface;
import br.com.gma.cliente.common.MainFormInterface;
import br.com.gma.server.common.entity.Produto;
import java.rmi.RemoteException;
import java.util.Collection;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alirio
 */
public class EstoqueForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form EstoqueForm
     */
    private AutenticadorInterface ai;
    private MainFormInterface mainInterface;
    private Collection<Produto> lstProduto;
    private Long pid;
    private Produto p;
    
    public EstoqueForm(AutenticadorInterface a, MainFormInterface mi, Long id) {
        ai = a;
        mainInterface = mi;
        pid = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jcbTipo = new javax.swing.JComboBox();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbProduto = new javax.swing.JComboBox();
        rbAdd = new javax.swing.JRadioButton();
        rbSub = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tfValue = new javax.swing.JFormattedTextField();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Controle de estoque");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Farinha Industrial", "Farinha Domestica", "Farelo", "" }));
        jcbTipo.setSelectedIndex(3);
        jcbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoItemStateChanged(evt);
            }
        });

        btnView.setText("Ver estoque");
        btnView.setEnabled(false);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo:");

        jLabel2.setText("Produto:");

        jcbProduto.setEnabled(false);
        jcbProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbProdutoItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbAdd);
        rbAdd.setSelected(true);
        rbAdd.setText("Adicionar ao estoque");

        buttonGroup1.add(rbSub);
        rbSub.setText("Subtrair do estoque");

        jLabel4.setText("Valor:");

        tfValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tfValue.setText("0");
        tfValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfValueFocusLost(evt);
            }
        });

        btnSave.setText("Salvar");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(rbAdd)
                                .addGap(18, 18, 18)
                                .addComponent(rbSub))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfValue, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAdd)
                    .addComponent(rbSub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoItemStateChanged
        if(jcbTipo.getSelectedIndex() == 3){
            jcbProduto.removeAllItems();
            jcbProduto.setSelectedItem(null);
            jcbProduto.setEnabled(false);
            btnView.setEnabled(false);
            btnSave.setEnabled(false);
            tfValue.setEnabled(false);
            return;
        }
        try {
            lstProduto = mainInterface.obterProdutoRemote().pesquisarProdutoByTipo(pid, jcbTipo.getSelectedIndex());
        } catch (RemoteException ex) {ex.printStackTrace();}
        Iterator it = lstProduto.iterator();
        jcbProduto.removeAllItems();
        while(it.hasNext()){
            jcbProduto.addItem(((Produto) it.next()).getNome_produto());
        }
        jcbProduto.addItem("");
        jcbProduto.setSelectedIndex(jcbProduto.getItemCount()-1);
        jcbProduto.setEnabled(true);
        btnView.setEnabled(false);
        tfValue.setEnabled(true);
    }//GEN-LAST:event_jcbTipoItemStateChanged

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        try {
            Float qtd = mainInterface.obterProdutoRemote().pesquisarProdutoByNome(jcbProduto.getSelectedItem().toString(), pid).getEstoque();
            JOptionPane.showMessageDialog(this, "Quantidade em estoque é: "+qtd);
        } catch (RemoteException ex) {ex.printStackTrace();}
        
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void tfValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValueFocusLost
        if(tfValue.getText().equals("") || jcbProduto.getSelectedIndex() == jcbProduto.getItemCount()-1)
            return;
        try{
            Long v = Long.parseLong(tfValue.getText());
            if(v >= 0)
                btnSave.setEnabled(true);
            else
                btnSave.setEnabled(false);
        }catch(NumberFormatException ex){
            ex.printStackTrace();
            btnSave.setEnabled(false);
        }
    }//GEN-LAST:event_tfValueFocusLost

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            p = mainInterface.obterProdutoRemote().pesquisarProdutoByNome(jcbProduto.getSelectedItem().toString(), pid);
            
            if(rbAdd.isSelected())
                p.setEstoque(p.getEstoque() + Long.parseLong(tfValue.getText()));
            if(rbSub.isSelected())
                p.setEstoque(p.getEstoque() - Long.parseLong(tfValue.getText()));
            
            mainInterface.obterProdutoRemote().updateProduto(p, pid);
        } catch (RemoteException ex) {ex.printStackTrace();}
        finally{
            tfValue.setText("0");
            btnView.setEnabled(false);
            btnSave.setEnabled(false);
            jcbProduto.removeAllItems();
            jcbProduto.setSelectedItem(null);
            jcbProduto.setEnabled(false);
            jcbTipo.setSelectedIndex(3);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jcbProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbProdutoItemStateChanged
        if(jcbProduto.getSelectedIndex() == jcbProduto.getItemCount()-1){
            btnView.setEnabled(false);
            btnSave.setEnabled(false);
            tfValue.setEnabled(false);
        }else{
            btnView.setEnabled(true);
            //btnSave.setEnabled(false);
            tfValue.setEnabled(true);
        }                 
    }//GEN-LAST:event_jcbProdutoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox jcbProduto;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JRadioButton rbAdd;
    private javax.swing.JRadioButton rbSub;
    private javax.swing.JFormattedTextField tfValue;
    // End of variables declaration//GEN-END:variables
}
