/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.gma.expedicao.presentation;

import br.com.gma.cliente.common.JCalendar;
import br.com.gma.cliente.common.MainFormInterface;
import br.com.gma.cliente.common.ProgressBarInterface;
import br.com.gma.relatorios.Carregamento;
import br.com.gma.relatorios.model.CarregamentoEntity;
import br.com.gma.relatorios.model.ProducaoEntity;
import static br.com.gma.server.common.entity.CONSTANTES.BIG_BAG;
import static br.com.gma.server.common.entity.CONSTANTES.BIG_BAG_SMALL;
import static br.com.gma.server.common.entity.CONSTANTES.DOMESTICA;
import static br.com.gma.server.common.entity.CONSTANTES.FARELO;
import static br.com.gma.server.common.entity.CONSTANTES.INDUSTRIAL;
import br.com.gma.server.common.entity.Pedido;
import java.awt.CardLayout;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alirio
 */
public class RelatorioForm extends javax.swing.JInternalFrame implements Runnable,ProgressBarInterface{

    /**
     * Creates new form RelatorioForm
     */
    private Carregamento carregamentoREL;
    private MainFormInterface servidor;
    private Collection<CarregamentoEntity> pedidos;
    private List<ProducaoEntity> producao;
    private List<CarregamentoEntity> rel;
    private final Long pid;
    private volatile int tt;
    public RelatorioForm(MainFormInterface servidor, Long p, String path, String path2) {
        initComponents();
        this.pid = p;
        this.servidor = servidor;
        carregamentoREL = new Carregamento(this,path, path2);
        pedidos = new HashSet<CarregamentoEntity>();
        producao = new ArrayList<ProducaoEntity>();
        rel = new ArrayList<CarregamentoEntity>();
        
        CardLayout card = (CardLayout)(pMain.getLayout());     
        card.show(panelIndustrial.getParent(), "INDUSTRIAL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        progressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pMain = new javax.swing.JPanel();
        panelIndustrial = new javax.swing.JPanel();
        cbDataInicialIndustrial = new JCalendar(true);
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbDataFinalIndustrial = new JCalendar(true);
        btnIndustrial = new javax.swing.JButton();
        pbarIndustrial = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hiIndustrial = new javax.swing.JFormattedTextField();
        hfIndustrial = new javax.swing.JFormattedTextField();
        panelDomestica = new javax.swing.JPanel();
        cbDataInicialDomestica = new JCalendar(true);
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbDataFinalDomestica = new JCalendar(true);
        btnDomestica = new javax.swing.JButton();
        pbarDomestica = new javax.swing.JProgressBar();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        hiDomestica = new javax.swing.JFormattedTextField();
        hfDomestica = new javax.swing.JFormattedTextField();
        panelFarelo = new javax.swing.JPanel();
        cbDataInicialFarelo = new JCalendar(true);
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbDataFinalFarelo = new JCalendar(true);
        btnFarelo = new javax.swing.JButton();
        pbarFarelo = new javax.swing.JProgressBar();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        hiFarelo = new javax.swing.JFormattedTextField();
        hfFarelo = new javax.swing.JFormattedTextField();
        panelBags = new javax.swing.JPanel();
        cbDataInicialBags = new JCalendar(true);
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cbDataFinalBags = new JCalendar(true);
        btnBags = new javax.swing.JButton();
        pbarBags = new javax.swing.JProgressBar();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        hiBags = new javax.swing.JFormattedTextField();
        hfBags = new javax.swing.JFormattedTextField();
        panelBagsPequeno = new javax.swing.JPanel();
        cbDataInicialBagsPequeno = new JCalendar(true);
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cbDataFinalBagsPequeno = new JCalendar(true);
        btnBagsPequeno = new javax.swing.JButton();
        pbarBagsPequeno = new javax.swing.JProgressBar();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        hiBagsPequeno = new javax.swing.JFormattedTextField();
        hfBagsPequeno = new javax.swing.JFormattedTextField();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btnRelatioDeCarga = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbDataInicialIndustrial1 = new JCalendar(true);
        cbDataFinalIndustrial1 = new JCalendar(true);
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        hiIndustrial1 = new javax.swing.JFormattedTextField();
        hfIndustrial1 = new javax.swing.JFormattedTextField();
        pbarIndustrial1 = new javax.swing.JProgressBar();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDialog1.setTitle("Gerando relatório");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setName("dialogProgress"); // NOI18N
        jDialog1.setResizable(false);

        jLabel1.setText("Progresso");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Cancelar");

        jButton2.setText("Ok");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jDialog1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, progressBar});

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Relatórios");

        pMain.setLayout(new java.awt.CardLayout());

        panelIndustrial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Data Inicial");

        jLabel9.setText("Data Final");

        btnIndustrial.setText("Gerar Relatorio Industrial");
        btnIndustrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndustrialActionPerformed(evt);
            }
        });

        pbarIndustrial.setStringPainted(true);

        jLabel10.setText("Hora Inicio");

        jLabel11.setText("Hora Fim");

        try {
            hiIndustrial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hiIndustrial.setText("05:00");

        try {
            hfIndustrial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hfIndustrial.setText("05:00");

        javax.swing.GroupLayout panelIndustrialLayout = new javax.swing.GroupLayout(panelIndustrial);
        panelIndustrial.setLayout(panelIndustrialLayout);
        panelIndustrialLayout.setHorizontalGroup(
            panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndustrialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbDataInicialIndustrial, 0, 128, Short.MAX_VALUE)
                    .addComponent(cbDataFinalIndustrial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hiIndustrial, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(hfIndustrial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbarIndustrial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelIndustrialLayout.createSequentialGroup()
                        .addComponent(btnIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 236, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelIndustrialLayout.setVerticalGroup(
            panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndustrialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDataInicialIndustrial)
                    .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(btnIndustrial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addComponent(hiIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hfIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pbarIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIndustrialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDataFinalIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(9, 9, 9))
        );

        pMain.add(panelIndustrial, "INDUSTRIAL");

        panelDomestica.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setText("Data Inicial");

        jLabel17.setText("Data Final");

        btnDomestica.setText("Gerar Relatorio Domestica");
        btnDomestica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDomesticaActionPerformed(evt);
            }
        });

        pbarDomestica.setStringPainted(true);

        jLabel18.setText("Hora Inicio");

        jLabel19.setText("Hora Fim");

        try {
            hiDomestica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hiDomestica.setText("05:00");

        try {
            hfDomestica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hfDomestica.setText("05:00");

        javax.swing.GroupLayout panelDomesticaLayout = new javax.swing.GroupLayout(panelDomestica);
        panelDomestica.setLayout(panelDomesticaLayout);
        panelDomesticaLayout.setHorizontalGroup(
            panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDomesticaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbDataFinalDomestica, 0, 128, Short.MAX_VALUE)
                    .addComponent(cbDataInicialDomestica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hiDomestica, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(hfDomestica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbarDomestica, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(panelDomesticaLayout.createSequentialGroup()
                        .addComponent(btnDomestica, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDomesticaLayout.setVerticalGroup(
            panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDomesticaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDataInicialDomestica)
                    .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(btnDomestica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addComponent(hiDomestica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hfDomestica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pbarDomestica, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomesticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDataFinalDomestica, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addContainerGap())
        );

        pMain.add(panelDomestica, "DOMESTICA");

        panelFarelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setText("Data Inicial");

        jLabel21.setText("Data Final");

        btnFarelo.setText("Gerar Relatorio Farelo");
        btnFarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFareloActionPerformed(evt);
            }
        });

        pbarFarelo.setStringPainted(true);

        jLabel22.setText("Hora Inicio");

        jLabel23.setText("Hora Fim");

        try {
            hiFarelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hiFarelo.setText("05:00");

        try {
            hfFarelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hfFarelo.setText("05:00");

        javax.swing.GroupLayout panelFareloLayout = new javax.swing.GroupLayout(panelFarelo);
        panelFarelo.setLayout(panelFareloLayout);
        panelFareloLayout.setHorizontalGroup(
            panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFareloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbDataInicialFarelo, 0, 128, Short.MAX_VALUE)
                    .addComponent(cbDataFinalFarelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hiFarelo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(hfFarelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbarFarelo, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(panelFareloLayout.createSequentialGroup()
                        .addComponent(btnFarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFareloLayout.setVerticalGroup(
            panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFareloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDataInicialFarelo)
                    .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(btnFarelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addComponent(hiFarelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hfFarelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pbarFarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFareloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDataFinalFarelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(9, 9, 9))
        );

        pMain.add(panelFarelo, "FARELO");

        panelBags.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel24.setText("Data Inicial");

        jLabel25.setText("Data Final");

        btnBags.setText("Gerar Relatorio Bag");
        btnBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagsActionPerformed(evt);
            }
        });

        pbarBags.setStringPainted(true);

        jLabel26.setText("Hora Inicio");

        jLabel27.setText("Hora Fim");

        try {
            hiBags.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hiBags.setText("05:00");

        try {
            hfBags.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hfBags.setText("05:00");

        javax.swing.GroupLayout panelBagsLayout = new javax.swing.GroupLayout(panelBags);
        panelBags.setLayout(panelBagsLayout);
        panelBagsLayout.setHorizontalGroup(
            panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBagsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbDataFinalBags, 0, 128, Short.MAX_VALUE)
                    .addComponent(cbDataInicialBags, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hiBags, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(hfBags))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbarBags, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(panelBagsLayout.createSequentialGroup()
                        .addComponent(btnBags, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBagsLayout.setVerticalGroup(
            panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBagsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDataInicialBags)
                    .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(btnBags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addComponent(hiBags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hfBags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pbarBags, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDataFinalBags, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addGap(9, 9, 9))
        );

        pMain.add(panelBags, "BAGS");

        panelBagsPequeno.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel28.setText("Data Inicial");

        jLabel29.setText("Data Final");

        btnBagsPequeno.setText("Gerar Relatorio Bag Pequeno");
        btnBagsPequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagsPequenoActionPerformed(evt);
            }
        });

        pbarBagsPequeno.setStringPainted(true);

        jLabel30.setText("Hora Inicio");

        jLabel31.setText("Hora Fim");

        try {
            hiBagsPequeno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hiBagsPequeno.setText("05:00");

        try {
            hfBagsPequeno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hfBagsPequeno.setText("05:00");

        javax.swing.GroupLayout panelBagsPequenoLayout = new javax.swing.GroupLayout(panelBagsPequeno);
        panelBagsPequeno.setLayout(panelBagsPequenoLayout);
        panelBagsPequenoLayout.setHorizontalGroup(
            panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBagsPequenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbDataInicialBagsPequeno, 0, 128, Short.MAX_VALUE)
                    .addComponent(cbDataFinalBagsPequeno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hiBagsPequeno, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(hfBagsPequeno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbarBagsPequeno, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(panelBagsPequenoLayout.createSequentialGroup()
                        .addComponent(btnBagsPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBagsPequenoLayout.setVerticalGroup(
            panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBagsPequenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDataInicialBagsPequeno)
                    .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(btnBagsPequeno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addComponent(hiBagsPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hfBagsPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pbarBagsPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBagsPequenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDataFinalBagsPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)))
                .addGap(9, 9, 9))
        );

        pMain.add(panelBagsPequeno, "BAGSPEQUENOS");

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("BigBag Pequeno");
        jToggleButton5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton5StateChanged(evt);
            }
        });
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setText("Big Bag");
        jToggleButton4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton4StateChanged(evt);
            }
        });

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("Farelo");
        jToggleButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton3StateChanged(evt);
            }
        });

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("Domestica");
        jToggleButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton2StateChanged(evt);
            }
        });

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setSelected(true);
        jToggleButton1.setText("Industrial");
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRelatioDeCarga.setText("Gerar relatório de tipo de carga");
        btnRelatioDeCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatioDeCargaActionPerformed(evt);
            }
        });

        jLabel12.setText("Data Inicial");

        jLabel13.setText("Data Final");

        jLabel14.setText("Hora Inicio");

        jLabel15.setText("Hora Fim");

        try {
            hiIndustrial1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hiIndustrial1.setText("05:00");

        try {
            hfIndustrial1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hfIndustrial1.setText("05:00");

        pbarIndustrial1.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbDataFinalIndustrial1, 0, 128, Short.MAX_VALUE)
                    .addComponent(cbDataInicialIndustrial1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hiIndustrial1)
                    .addComponent(hfIndustrial1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbarIndustrial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRelatioDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDataInicialIndustrial1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14)
                        .addComponent(hiIndustrial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRelatioDeCarga)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hfIndustrial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pbarIndustrial1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDataFinalIndustrial1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jToggleButton1, jToggleButton2, jToggleButton3, jToggleButton4, jToggleButton5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton5))
                .addGap(18, 18, 18)
                .addComponent(pMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        if(jToggleButton1.isSelected()){
            CardLayout card = (CardLayout)(pMain.getLayout());
            card.show(panelIndustrial.getParent(), "INDUSTRIAL");
        }
    }//GEN-LAST:event_jToggleButton1StateChanged

    private void jToggleButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton2StateChanged
        if(jToggleButton2.isSelected()){
            CardLayout card = (CardLayout)(pMain.getLayout());
            card.show(panelDomestica.getParent(), "DOMESTICA");
        }
    }//GEN-LAST:event_jToggleButton2StateChanged

    private void jToggleButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton3StateChanged
        if(jToggleButton3.isSelected()){
            CardLayout card = (CardLayout)(pMain.getLayout());
            card.show(panelFarelo.getParent(), "FARELO");
        }
    }//GEN-LAST:event_jToggleButton3StateChanged

    private void jToggleButton4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton4StateChanged
        if(jToggleButton4.isSelected()){
            CardLayout card = (CardLayout)(pMain.getLayout());
            card.show(panelBagsPequeno.getParent(), "BAGS");
        }
    }//GEN-LAST:event_jToggleButton4StateChanged

    private void jToggleButton5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton5StateChanged
        if(jToggleButton5.isSelected()){
            CardLayout card = (CardLayout)(pMain.getLayout());
            card.show(panelBagsPequeno.getParent(), "BAGSPEQUENOS");
        }
    }//GEN-LAST:event_jToggleButton5StateChanged

    private void btnIndustrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndustrialActionPerformed
        doRel(INDUSTRIAL);
    }//GEN-LAST:event_btnIndustrialActionPerformed

    private void btnDomesticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDomesticaActionPerformed
        doRel(DOMESTICA);
    }//GEN-LAST:event_btnDomesticaActionPerformed

    private void btnFareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFareloActionPerformed
        doRel(FARELO);
    }//GEN-LAST:event_btnFareloActionPerformed

    private void btnBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagsActionPerformed
        doRel(BIG_BAG);
    }//GEN-LAST:event_btnBagsActionPerformed

    private void btnBagsPequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagsPequenoActionPerformed
        doRel(BIG_BAG_SMALL);
    }//GEN-LAST:event_btnBagsPequenoActionPerformed

    private void btnRelatioDeCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatioDeCargaActionPerformed
        producao.clear();
        setPercent(5,0);
        tt = 5;
        setStateButton(5,false);
        setPercent(5,2);
        Date i = null;
        Date f = null;
        setPercent(5,4);
        i = ((JCalendar)cbDataInicialIndustrial1).date();
        f = ((JCalendar)cbDataFinalIndustrial1).date();
        i.setHours(Integer.parseInt(hiIndustrial1.getText().substring(0, 2)));// 00:00
        i.setMinutes(Integer.parseInt(hiIndustrial1.getText().substring(3, 5)));
        f.setHours(Integer.parseInt(hfIndustrial1.getText().substring(0, 2)));
        f.setMinutes(Integer.parseInt(hfIndustrial1.getText().substring(3, 5)));
        setPercent(5,6);
        
        setPercent(5,6);
        ProducaoEntity pe = null;
        Iterator it;
        Collection<Pedido> arrayProducao = null;
        try {
            for(int c = 0; c <= 4;c++){
                arrayProducao = servidor.obterPedidoRemote().pesquisarPedido(pid,i,f,c);
                
                switch(c){
                    case 0:
                        pe = new ProducaoEntity();
                        pe.setCarregamentotipo("INDUSTRIAL");
                        pe.setCargaclose(0);
                        pe.setCargaopen(0);
                        break;
                    case 1:
                        pe = new ProducaoEntity();
                        pe.setCarregamentotipo("DOMESTICA");
                        pe.setCargaclose(0);
                        pe.setCargaopen(0);
                        break;
                    case 2:
                        pe = new ProducaoEntity();
                        pe.setCarregamentotipo("FARELO");
                        pe.setCargaclose(0);
                        pe.setCargaopen(0);
                        break;
                    case 3:
                        pe = new ProducaoEntity();
                        pe.setCarregamentotipo("BAG");
                        pe.setCargaclose(0);
                        pe.setCargaopen(0);
                        break;
                    case 4:
                        pe = new ProducaoEntity();
                        pe.setCarregamentotipo("BAG PEQUENO");
                        pe.setCargaclose(0);
                        pe.setCargaopen(0);
                        break;
                    default:
                        pe = new ProducaoEntity();
                        System.out.println("Default");
                        break;
                }
                if(arrayProducao == null){
                    System.out.println("Tipo: "+c+" nullo");
                }else{
                    System.out.println("size: "+arrayProducao.size());
                    it = arrayProducao.iterator();
                    Pedido producaoentity;
                    while(it.hasNext()){
                        producaoentity = (Pedido)it.next();
                        
                        if(producaoentity.getCarga_fechada() == null || producaoentity.getCarga_aberta() == null){
                            System.out.print("Close: "+producaoentity.getCarga_fechada()+"\t");
                            System.out.println("Open: "+producaoentity.getCarga_fechada());
                        }else{
                            pe.setCargaclose(pe.getCargaclose() + producaoentity.getCarga_fechada());
                            pe.setCargaopen(pe.getCargaopen() + producaoentity.getCarga_aberta());
                        }
                        
                    }
                }                
                producao.add(pe);
            }
            
            setPercent(5,10);
        } catch (RemoteException ex) { ex.printStackTrace();setStateButton(5,true); } 
          catch (Exception ex) { ex.printStackTrace();setStateButton(5,true);}
        /*if(arrayProducao == null){
            JOptionPane.showMessageDialog(this, "Sem resultados", "Pesquisa vazia",JOptionPane.INFORMATION_MESSAGE);
            setPercent(5,0);
            setStateButton(5,true);
            return;
        }*/
        setPercent(5,30);
        new Thread(this).start();
    }//GEN-LAST:event_btnRelatioDeCargaActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed
    
    private void doRel(int tipo){
        setPercent(tipo,0);
        tt = tipo;
        setStateButton(tipo,false);
        setPercent(tipo,2);
        Date i = null;
        Date f = null;
        setPercent(tipo,4);
        switch(tipo){
            case 0:
                i = ((JCalendar)cbDataInicialIndustrial).date();
                f = ((JCalendar)cbDataFinalIndustrial).date();
                i.setHours(Integer.parseInt(hiIndustrial.getText().substring(0, 2)));// 00:00
                i.setMinutes(Integer.parseInt(hiIndustrial.getText().substring(3, 5)));
                f.setHours(Integer.parseInt(hfIndustrial.getText().substring(0, 2)));
                f.setMinutes(Integer.parseInt(hfIndustrial.getText().substring(3, 5)));
                setPercent(tipo,6);
                break;
            case 1:
                i = ((JCalendar)cbDataInicialDomestica).date();
                f = ((JCalendar)cbDataFinalDomestica).date();
                i.setHours(Integer.parseInt(hiDomestica.getText().substring(0, 2)));// 00:00
                i.setMinutes(Integer.parseInt(hiDomestica.getText().substring(3, 5)));
                f.setHours(Integer.parseInt(hfDomestica.getText().substring(0, 2)));
                f.setMinutes(Integer.parseInt(hfDomestica.getText().substring(3, 5)));
                break;
            case 2:
                i = ((JCalendar)cbDataInicialFarelo).date();
                f = ((JCalendar)cbDataFinalFarelo).date();
                i.setHours(Integer.parseInt(hiFarelo.getText().substring(0, 2)));// 00:00
                i.setMinutes(Integer.parseInt(hiFarelo.getText().substring(3, 5)));
                f.setHours(Integer.parseInt(hfFarelo.getText().substring(0, 2)));
                f.setMinutes(Integer.parseInt(hfFarelo.getText().substring(3, 5)));
                break;
            case 3:
                i = ((JCalendar)cbDataInicialBags).date();
                f = ((JCalendar)cbDataFinalBags).date();
                i.setHours(Integer.parseInt(hiBags.getText().substring(0, 2)));// 00:00
                i.setMinutes(Integer.parseInt(hiBags.getText().substring(3, 5)));
                f.setHours(Integer.parseInt(hfBags.getText().substring(0, 2)));
                f.setMinutes(Integer.parseInt(hfBags.getText().substring(3, 5)));
                break;
            case 4:
                i = ((JCalendar)cbDataInicialBagsPequeno).date();
                f = ((JCalendar)cbDataFinalBagsPequeno).date();
                i.setHours(Integer.parseInt(hiBagsPequeno.getText().substring(0, 2)));// 00:00
                i.setMinutes(Integer.parseInt(hiBagsPequeno.getText().substring(3, 5)));
                f.setHours(Integer.parseInt(hfBagsPequeno.getText().substring(0, 2)));
                f.setMinutes(Integer.parseInt(hfBagsPequeno.getText().substring(3, 5)));
                break;
            
        }        
        
        setPercent(tipo,6);
        try {
            pedidos = servidor.obterPedidoRemote().pesquisarPedido(pid,i,f,"Finalizado",tipo);
            setPercent(tipo,10);
        } catch (RemoteException ex) { ex.printStackTrace();setStateButton(tipo,true); } 
          catch (Exception ex) { ex.printStackTrace();setStateButton(tipo,true);}
        if(pedidos == null){
            JOptionPane.showMessageDialog(this, "Sem resultados", "Pesquisa vazia",JOptionPane.INFORMATION_MESSAGE);
            setPercent(tipo,0);
            setStateButton(tipo,true);
            return;
        }
        
        Iterator it = pedidos.iterator();
        Pedido x;
        rel.clear();
        setPercent(tipo,15);
        int h,m;
        Float t1,t2;
        Float intt;
        String time;
        while(it.hasNext()){            
            x = (Pedido) it.next();
            time = x.getDuracao_carregamento();
            if(time.contains("d"))
                time=time.substring(3, time.length());
            
            h = Integer.parseInt(time.substring(0, 2));
            m = Integer.parseInt(time.substring(3, 5));
            if(x.getQuant_estoque() == null)
                t2=0f;
            else
                t2=x.getQuant_estoque();
            
            if(x.getQuant_Expedido() == null)
                t1=0f;
            else
                t1=x.getQuant_Expedido();
            //String str = Float.toString(t);
            //str = str.substring(0, str.indexOf("."));
            intt = (((t1+t2)/((h*60)+m))*60);
            rel.add(new CarregamentoEntity(
                    x.getProduto().getNome_produto(),
                    x.getQuant(),
                    x.getCliente().getNome_cliente(),
                    x.getPlaca_do_pedido(),
                    x.getCarga(),
                    x.getPedido_expedido(),
                    x.getPedido_finalizado(),
                    x.getAvaria(),
                    time,
                    intt,//media
                    x.getQuant_Expedido(),
                    x.getQuant_estoque()));
        }
        Collections.sort(rel);
        setPercent(tipo,30);
        new Thread(this).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBags;
    private javax.swing.JButton btnBagsPequeno;
    private javax.swing.JButton btnDomestica;
    private javax.swing.JButton btnFarelo;
    private javax.swing.JButton btnIndustrial;
    private javax.swing.JButton btnRelatioDeCarga;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbDataFinalBags;
    private javax.swing.JComboBox cbDataFinalBagsPequeno;
    private javax.swing.JComboBox cbDataFinalDomestica;
    private javax.swing.JComboBox cbDataFinalFarelo;
    private javax.swing.JComboBox cbDataFinalIndustrial;
    private javax.swing.JComboBox cbDataFinalIndustrial1;
    private javax.swing.JComboBox cbDataInicialBags;
    private javax.swing.JComboBox cbDataInicialBagsPequeno;
    private javax.swing.JComboBox cbDataInicialDomestica;
    private javax.swing.JComboBox cbDataInicialFarelo;
    private javax.swing.JComboBox cbDataInicialIndustrial;
    private javax.swing.JComboBox cbDataInicialIndustrial1;
    private javax.swing.JFormattedTextField hfBags;
    private javax.swing.JFormattedTextField hfBagsPequeno;
    private javax.swing.JFormattedTextField hfDomestica;
    private javax.swing.JFormattedTextField hfFarelo;
    private javax.swing.JFormattedTextField hfIndustrial;
    private javax.swing.JFormattedTextField hfIndustrial1;
    private javax.swing.JFormattedTextField hiBags;
    private javax.swing.JFormattedTextField hiBagsPequeno;
    private javax.swing.JFormattedTextField hiDomestica;
    private javax.swing.JFormattedTextField hiFarelo;
    private javax.swing.JFormattedTextField hiIndustrial;
    private javax.swing.JFormattedTextField hiIndustrial1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel panelBags;
    private javax.swing.JPanel panelBagsPequeno;
    private javax.swing.JPanel panelDomestica;
    private javax.swing.JPanel panelFarelo;
    private javax.swing.JPanel panelIndustrial;
    private javax.swing.JProgressBar pbarBags;
    private javax.swing.JProgressBar pbarBagsPequeno;
    private javax.swing.JProgressBar pbarDomestica;
    private javax.swing.JProgressBar pbarFarelo;
    private javax.swing.JProgressBar pbarIndustrial;
    private javax.swing.JProgressBar pbarIndustrial1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            if(tt==5)
                carregamentoREL.imprimirProducao(producao,tt);
            else
                carregamentoREL.imprimir(rel,tt);
        } catch (Exception ex) {ex.printStackTrace();setStateButton(tt,true);setPercent(tt,0); }
    }    
    @Override
    public void setStateButton(int b, boolean s) {
        switch(b){
            case 0:
                btnIndustrial.setEnabled(s);
                break;
            case 1:
                btnDomestica.setEnabled(s);
                break;
            case 2:
                btnFarelo.setEnabled(s);
                break;
            case 3:
                btnBags.setEnabled(s);
                break;
            case 4:
                btnBagsPequeno.setEnabled(s);
                break;  
            case 5:
                btnRelatioDeCarga.setEnabled(s);
                break;
        }
    }
    @Override
    public void setPercent(int p, int f) {
        switch(p){
            case 0:
                pbarIndustrial.setValue(f);
                break;
            case 1:
                pbarDomestica.setValue(f);
                break;
            case 2:
                pbarFarelo.setValue(f);
                break;
            case 3:
                pbarBags.setValue(f);
                break;
            case 4:
                pbarBagsPequeno.setValue(f);
                break;
            case 5:
                pbarIndustrial1.setValue(f);
                break;
        }
    }

    @Override
    public void setPercent(int p, int f, String process) {
        switch(p){
            case 0:
                pbarIndustrial.setValue(f);
                break;
            case 1:
                pbarDomestica.setValue(f);
                break;
            case 2:
                pbarFarelo.setValue(f);
                break;
            case 3:
                pbarBags.setValue(f);
                break;
            case 4:
                pbarBagsPequeno.setValue(f);
                break;
            case 5:
                pbarIndustrial1.setValue(f);
                break;
        }
    }
}

